dark-mode: true
auto-commits: false

auto-lint: true
lint-cmd:
  - "./scripts/aider-lint.sh"

read:
  - prompts/conventions.md

# model: anthropic/claude-sonnet-4-20250514
model: anthropic/claude-sonnet-4-5-20250929
